[build]
  base = "web/"
  command = "npm run build"
  publish = "public/"

[[redirects]]
  from = "freshbakininteractive.com"
  to = "/interactive"
  force = true
  status = 200
[[redirects]]
  from = "www.freshbakininteractive.com"
  to = "/interactive"
  force = true
  status = 200
[[redirects]]
  from = "freshbakininteractive.com/*"
  to = "freshbakin.com/:splat"
  status = 301
[[redirects]]
  from = "www.freshbakininteractive.com/*"
  to = "www.freshbakin.com/:splat"
  status = 301