[build]
  base = "web/"
  command = "npm run build"
  publish = "public/"

# [[redirects]]
#   from = "freshbakininteractive.com"
#   to = "/interactive"
#   force = true
#   status = 200
[[redirects]]
  from = "https://www.freshbakininteractive.com"
  to = "https://www.freshbakin.com/interactive"
  status = 301
  force = true
# [[redirects]]
#   from = "freshbakininteractive.com/*"
#   to = "freshbakin.com/:splat"
#   status = 301
#   force = true
# [[redirects]]
#   from = "www.freshbakininteractive.com/*"
#   to = "www.freshbakin.com/:splat"
#   status = 301
#   force = true